version: "3"

services:
  deepdanbooru-web:
    image: deepdanbooru-web:gpu
    build: .
    container_name: deepdanbooru-web
    restart: always
    command: ["web", "--project-path", "/root/deepdanbooru/project", "--port", "80", "--allow-gpu"]
    ports:
      - "15100:80"
    volumes:
      - ./project:/root/deepdanbooru/project
      - ./log:/root/deepdanbooru/log
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
