version: "3"

services:
  deepdanbooru-web:
    image: deepdanbooru-web
    build: .
    container_name: deepdanbooru-web
    restart: always
    command: ["web", "--project-path", "/root/deepdanbooru/project", "--port", "80"]
    ports:
      - "15100:80"
    volumes:
      - ./project:/root/deepdanbooru/project
      - ./log:/root/deepdanbooru/log
