version: "3"

services:
  deepdanbooru-web:
    image: deepdanbooru_web
    build: .
    container_name: deepdanbooru-web
    restart: always
    ports:
      - "15100:80"
    volumes:
      - ./logs:/root/deepdanbooru/logs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
